apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
       - 10.0.1.32/32
       - 10.0.1.54/32
       - 10.0.1.55/32
       - 10.0.1.56/32
       - 10.0.1.57/32
       - 10.0.1.58/32
       - 10.0.1.61/32
#      - 128.120.136.32/32
#      - 128.120.136.54/32
#      - 128.120.136.55/32
#      - 128.120.136.56/32
#      - 128.120.136.61/32
