- hosts: all
  become: yes
  tasks:
   - name: Update and upgrade apt packages
     become: true
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400

   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

# this is needed on each of the nodes so they can use nfs persistent volumes
   - name: install nfs client
     apt:
       name: nfs-common
       state: present

   - name: get the gnupg package
     apt:
       name: gnupg
       state: present

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet=1.14.0-00
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm=1.14.0-00
       state: present

   - name: create default directory
     become: yes
     file:
       path: /etc/default
       state: directory
       mode: 0755

# this is required because the nodeip was incorrect by default and the apiserver
# was unable to locate worker pods.
# only execute this for the development environment (the when statement)
   - name: set the kubelet node port in the default
     copy:
       content: "KUBELET_EXTRA_ARGS=--node-ip={{ansible_enp0s8.ipv4.address}}"
       dest: /etc/default/kubelet
     when: dev_env

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl=1.14.0-00
       state: present
       force: yes
